version: "3.8"

services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - 9090:9090
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --storage.tsdb.retention.time=7d
      - --storage.tsdb.retention.size=0
      - --storage.tsdb.wal-compression
      - --web.enable-lifecycle
    volumes:
      - ./prometheus-config.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-storage:/prometheus
    networks:
      - safefoods-app-network
    restart: unless-stopped

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3002:3000
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana-storage:/var/lib/grafana
    networks:
      - safefoods-app-network
    restart: unless-stopped

  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - 3100:3100
    volumes:
      - ./loki-config.yml:/etc/loki/local-config.yaml:ro
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - safefoods-app-network
    restart: unless-stopped

  tempo:
    container_name: tempo
    image: grafana/tempo:latest
    ports:
      - "3200:3200" # HTTP UI & API
      - "4317:4317" # OTLP gRPC receiver
      - "4318:4318" # OTLP HTTP receiver
    volumes:
      - ./tempo-config.yaml:/etc/tempo.yaml:ro
    command: ["-config.file=/etc/tempo.yaml"]
    networks:
      - safefoods-app-network
    restart: unless-stopped

networks:
  safefoods-app-network:
    external: true

volumes:
  grafana-storage:
    external: true
    name: monit_grafana-storage
  prometheus-storage:
    external: true
    name: monit_prometheus-storage
