global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "safefoods-api"
    static_configs:
      - targets: ["api.safefoods.com.bd"]
  - job_name: "safefoods-api-dev"
    static_configs:
      - targets: ["safefoods-app:8000"]
